import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-white text-black leading-normal p-0 m-0 dark:bg-black dark:text-white'>{children}</body>
    </html>
  )
}
