import './globals.css';
import { ThemeProvider } from './context/store'; 

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html className='w-full h-full p-0 m-0 overflow-hidden' lang="en">
        <body className='w-full h-full p-0 m-0 bg-white text-black dark:bg-black dark:text-white'>
          <ThemeProvider>
            {children}
          </ThemeProvider>
        </body>
      </html>
  )
}
